module.exports = {
    onlineClass:[
        {
            link:"",
            linkname:"WEB大前端就业班"
        },
        {
            link:"",
            linkname:"PHP工程师就业班"
        },
        {
            link:"",
            linkname:"Java Web工程师就业班"
        },
        {
            link:"",
            linkname:"UI/UX设计师就业班"
        }
    ],
    professionalCourses:[
        {
            link:"#",
            linkname:"Android架构模式详解之MVC/MVP/MVVM",
            linkimg:"android.jpg",
            classTime:"4小时  |  门课",
            price:"¥149.00",
            originalPrice:"¥299.00",
            studentCount:"31人学习",
        },
        {   
            link:"#",
            linkname:"开发自己的影评小程序",
            linkimg:"smallRoutine.jpg",
            classTime:"10小时  |  门课",
            price:"¥199.00",
            originalPrice:"¥299.00",
            studentCount:"10人学习",
        },
        {
            link:"#",
            linkname:'Python利器，超凡蜘蛛带你"爬"世界',
            linkimg:"python.jpg",
            classTime:"18小时  |  门课",
            price:"¥349.00",
            originalPrice:"¥499.00",
            studentCount:"232人学习",
        },
        {
            link:"#",
            linkname:"JavaScript编程技巧与实战",
            linkimg:"js.jpg",
            classTime:"8小时  |  门课",
            price:"¥79.00",
            originalPrice:"¥129.00",
            studentCount:"34人学习",
        }
    ],
    excellentProgrammer:[
        {
            link:"",
            linkTitle:["12天脱产学习，冲刺年薪二十万"],
            linkSubtitle:""
        },
        {
            link:"",
            linkTitle:"",
            linkSubtitle:""
        },
        {
            link:"",
            linkTitle:["20人小班教学，全力打造前端精英"],
            linkSubtitle:"了解更多>"
        },
        {
            link:"",
            linkTitle:"",
            linkSubtitle:""
        },
        {
            link:"",
            linkTitle:["0基础通道，让未来充满光明"],
            linkSubtitle:"点击咨询>"
        },
        {
            link:"",
            linkTitle:["测试专业度，未来薪资先知道"],
            linkSubtitle:"点击测试>"
        },
        {
            link:"",
            linkTitle:"",
            linkSubtitle:""
        },
        {
            link:"",
            linkTitle:["100%保就业, 月薪8000起"],
            linkSubtitle:"点击测试>"
        }

    ],
    DevilProgrammer:[
        {
            link:"",
            linkTitle:"魔鬼程序员，极客线下高端培训",
            linkSubtitle:"<了解详情",
            linkImg:"mogui1.jpg"
        },
        {
            link:"",
            linkTitle:"学习前导课，提升入学可能",
            linkSubtitle:"<前导课入口",
            linkImg:"mogui2.jpg"
        },
        {
            link:"",
            linkTitle:"全栈Web高级工程师，首期学费全免",
            linkSubtitle:"了解详情>",
            linkImg:"mogui2.jpg"
        },
        {
            link:"",
            linkTitle:"填写自荐信，抢占名额",
            linkSubtitle:"报名入口>",
            linkImg:"mogui2.jpg"
        }  
    ],
    careerColleges:[
        {
            link:"",
            linkTitle:"Web 前端工程师",
            linkImg:"zhiye1.jpg"
        },
        {
            link:"",
            linkTitle:"Python Web 工程师",
            linkImg:"zhiye2.jpg"
        },
        {
            link:"",
            linkTitle:"Go 语言工程师",
            linkImg:"zhiye3.jpg"
        },
        {
            link:"",
            linkTitle:"ios 工程师",
            linkImg:"zhiye4.jpg" 
        },
        {
            link:"",
            linkTitle:"微信小程序工程师",
            linkImg:"zhiye5.jpg" 
        }
    ],
    vipClass:[
        {
            link:"",
            linkImg:"1.png",
            linkTitle:"Android",
            linkSubtitle:"90门课程"
        },
        {
            link:"",
            linkImg:"2.png",
            linkTitle:"ios",
            linkSubtitle:"51门课程"
        },
        {
            link:"",
            linkImg:"3.png",
            linkTitle:"Swift语言",
            linkSubtitle:"11门课程"
        },
        {
            link:"",
            linkImg:"4.png",
            linkTitle:"HTML5开发",
            linkSubtitle:"116门课程"
        },
        {
            link:"",
            linkImg:"5.png",
            linkTitle:"JavaScript",
            linkSubtitle:"90门课程"
        },
        {
            link:"",
            linkImg:"6.png",
            linkTitle:"Node.js",
            linkSubtitle:"90门课程"
        },
        {
            link:"",
            linkImg:"7.png",
            linkTitle:"C语言",
            linkSubtitle:"17门课程"
        },
        {
            link:"",
            linkImg:"8.png",
            linkTitle:"Java语言",
            linkSubtitle:"17门课程"
        },
        {
            link:"",
            linkImg:"9.png",
            linkTitle:"PHP语言",
            linkSubtitle:"23门课程"
        },
        {
            link:"",
            linkImg:"10.png",
            linkTitle:"JavaWeb",
            linkSubtitle:"64门课程"
        },
        {
            link:"",
            linkImg:"11.png",
            linkTitle:"Python",
            linkSubtitle:"38门课程"
        },
        {
            link:"",
            linkImg:"12.png",
            linkTitle:"Cocos2d-x游戏开发",
            linkSubtitle:"89门课程"
        }
    ]
}