module.exports = {
    onlineClass:[
        {
            link:"",
            linkname:"WEB大前端就业班"
        },
        {
            link:"",
            linkname:"PHP工程师就业班"
        },
        {
            link:"",
            linkname:"Java Web工程师就业班"
        },
        {
            link:"",
            linkname:"UI/UX设计师就业班"
        }
    ],
    professionalCourses:[
        {
            link:"#",
            linkname:"Android架构模式详解之MVC/MVP/MVVM",
            linkimg:"android.jpg",
            classTime:"4小时  |  门课",
            price:"¥149.00",
            originalPrice:"¥299.00",
            studentCount:"31人学习",
        },
        {   
            link:"#",
            linkname:"开发自己的影评小程序",
            linkimg:"smallRoutine.jpg",
            classTime:"10小时  |  门课",
            price:"¥199.00",
            originalPrice:"¥299.00",
            studentCount:"10人学习",
        },
        {
            link:"#",
            linkname:'Python利器，超凡蜘蛛带你"爬"世界',
            linkimg:"python.jpg",
            classTime:"18小时  |  门课",
            price:"¥349.00",
            originalPrice:"¥499.00",
            studentCount:"232人学习",
        },
        {
            link:"#",
            linkname:"JavaScript编程技巧与实战",
            linkimg:"js.jpg",
            classTime:"8小时  |  门课",
            price:"¥79.00",
            originalPrice:"¥129.00",
            studentCount:"34人学习",
        }
    ],
    excellentProgrammer:[
        {
            link:"",
            linkTitle:["12天脱产学习，冲刺年薪二十万"],
            linkSubtitle:""
        },
        {
            link:"",
            linkTitle:"",
            linkSubtitle:""
        },
        {
            link:"",
            linkTitle:["20人小班教学，全力打造前端精英"],
            linkSubtitle:"了解更多>"
        },
        {
            link:"",
            linkTitle:"",
            linkSubtitle:""
        },
        {
            link:"",
            linkTitle:["0基础通道，让未来充满光明"],
            linkSubtitle:"点击咨询>"
        },
        {
            link:"",
            linkTitle:["测试专业度，未来薪资先知道"],
            linkSubtitle:"点击测试>"
        },
        {
            link:"",
            linkTitle:"",
            linkSubtitle:""
        },
        {
            link:"",
            linkTitle:["100%保就业, 月薪8000起"],
            linkSubtitle:"点击测试>"
        }

    ],
    DevilProgrammer:[
        {
            link:"",
            linkTitle:"魔鬼程序员，极客线下高端培训",
            linkSubtitle:"<了解详情",
            linkImg:"mogui1.jpg"
        },
        {
            link:"",
            linkTitle:"学习前导课，提升入学可能",
            linkSubtitle:"<前导课入口",
            linkImg:"mogui2.jpg"
        },
        {
            link:"",
            linkTitle:"全栈Web高级工程师，首期学费全免",
            linkSubtitle:"了解详情>",
            linkImg:"mogui2.jpg"
        },
        {
            link:"",
            linkTitle:"填写自荐信，抢占名额",
            linkSubtitle:"报名入口>",
            linkImg:"mogui2.jpg"
        }  
    ]
}